sso-operator:
  dex:
    grpcHost: "dex.jx"
dex:
  certs:
    # Image with OpenSSL and Kubectl
    image: rawlingsj80/openssl
    imageTag: "wip1"
  domain: "dex-jx.{{ .Requirements.ingress.domain }}"
  connectors:
    github:
      config:
        clientID: "{{ .Parameters.sso.dashboardAuthID }}"
        clientSecret: "{{ .Parameters.sso.dashboardAuthSecret }}" # pragma: allowlist secret
        orgs:
        - "{{ .Parameters.sso.dashboardAuthOrg }}"
