
{{- if .Values.CJXDChartmuseum }}
apiVersion: v1
data:
  BASIC_AUTH_PASS: {{ .Values.CJXDChartmuseum.password | b64enc | quote }}
  BASIC_AUTH_USER: {{ .Values.CJXDChartmuseum.username | b64enc | quote }}
kind: Secret
metadata:
  annotations:
    jenkins.io/chart: env
    jenkins.io/credentials-keybinding-password: BASIC_AUTH_PASS
    jenkins.io/credentials-keybinding-username: BASIC_AUTH_USER
  labels:
    heritage: Tiller
    jenkins.io/chart-release: jenkins-x
    jenkins.io/credentials-type: usernamePassword
    jenkins.io/namespace: jx
    release: jenkins-x
  name: cloudbees-cjxd-chartmuseum
  namespace: jx
type: Opaque
{{- end }}